# Generated by Django 3.1.3 on 2020-11-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trayectoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=100)),
                ('porcentaje', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='informacion_personal',
            name='edad',
            field=models.IntegerField(max_length=3),
        ),
    ]
