# Generated by Django 3.1.3 on 2020-11-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0004_auto_20201107_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion_personal',
            name='nacimiento',
            field=models.CharField(max_length=50),
        ),
    ]
