# Generated by Django 3.1.3 on 2020-11-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0005_auto_20201107_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='conocimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_conocimiento', models.CharField(max_length=100)),
                ('porcentaje_conocimiento', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='trayectoria',
        ),
    ]
