# Generated by Django 3.1.3 on 2020-11-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0006_auto_20201107_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='trayectoria_academica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trayectoria', models.CharField(max_length=100)),
                ('ano_inicio', models.CharField(max_length=5)),
                ('ano_termino', models.CharField(max_length=10)),
                ('nombre_institucion', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trayectoria_laboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trayectoria', models.CharField(max_length=100)),
                ('ano_inicio', models.CharField(max_length=5)),
                ('ano_termino', models.CharField(max_length=10)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
