# Generated by Django 3.1.3 on 2020-11-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0007_trayectoria_academica_trayectoria_laboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayectoria_academica',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
