# Generated by Django 3.1.3 on 2020-11-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0008_auto_20201107_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayectoria_laboral',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
