# Generated by Django 3.1.3 on 2020-11-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0009_auto_20201107_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion_personal',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trayectoria_academica',
            name='ano_inicio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trayectoria_academica',
            name='ano_termino',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trayectoria_academica',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trayectoria_laboral',
            name='ano_inicio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trayectoria_laboral',
            name='ano_termino',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trayectoria_laboral',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
